### ISSUE TITLE
CSS separator vs division sign

### ISSUE THREAD

**Issue by flachware** [lore-w/math-calc#1]
How does the math-calc plugin handle edge cases, is there a way to escape `/` in the example below?
```css
div {
  font: 16px / 2;
  grid-column: 1 / 4;
}
```
